CREATE TABLE `csvdata` (
  `DIVISION` varchar(3) NOT NULL,
  `MATCH_DATE` date NOT NULL,
  `HOME_TEAM` varchar(30) NOT NULL,
  `AWAY_TEAM` varchar(30) NOT NULL,
  `FT_HOME_GOALS` int(11) DEFAULT NULL,
  `FT_AWAY_GOALS` int(11) DEFAULT NULL,
  `FT_RESULT` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`DIVISION`,`MATCH_DATE`,`HOME_TEAM`,`AWAY_TEAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
