CREATE TABLE `csvdata` (
  `ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `DIVISION` varchar(3) NOT NULL,
  `MATCH_DATE` date NOT NULL,
  `HOME_TEAM` varchar(30) NOT NULL,
  `AWAY_TEAM` varchar(30) NOT NULL,
  `FT_HOME_GOALS` int(11) DEFAULT NULL,
  `FT_AWAY_GOALS` int(11) DEFAULT NULL,
  `FT_RESULT` varchar(1) DEFAULT NULL,
  `STATUS` varchar(15) DEFAULT NULL,		
  PRIMARY KEY (`ID`,`DIVISION`,`MATCH_DATE`,`HOME_TEAM`,`AWAY_TEAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `martingale`.`bet` (
  `idBET` INT NOT NULL AUTO_INCREMENT,
  `FIXTURE_ID` MEDIUMINT NOT NULL,
  `AMOUNT` INT NULL,
  `ODD` INT NULL,
  `TEAM` VARCHAR(30) NULL,
  `BET` VARCHAR(1) NULL,
  `DATE` DATE NULL,
  `RESULT` VARCHAR(15),
  PRIMARY KEY (`idBET`))
COMMENT = ' ';