
CREATE TABLE `csvdata` (
  `ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `DIVISION` varchar(3) NOT NULL,
  `MATCH_DATE` date NOT NULL,
  `HOME_TEAM` varchar(30) NOT NULL,
  `AWAY_TEAM` varchar(30) NOT NULL,
  `FT_HOME_GOALS` int(11) DEFAULT NULL,
  `FT_AWAY_GOALS` int(11) DEFAULT NULL,
  `FT_RESULT` varchar(1) DEFAULT NULL,
  `STATUS` varchar(15) DEFAULT NULL,		
  PRIMARY KEY (`ID`,`DIVISION`,`MATCH_DATE`,`HOME_TEAM`,`AWAY_TEAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `martingale`.`bet` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIXTURE_ID` MEDIUMINT NOT NULL,
  `AMOUNT` FLOAT NULL,
  `ODD` FLOAT NULL,
  `TEAM` VARCHAR(30) NULL,
  `BET` VARCHAR(1) NULL,
  `DATE` DATE NULL,
  `RESULT` VARCHAR(15),
  PRIMARY KEY (`ID`))
COMMENT = '	';

CREATE TABLE `martingale`.`sequence` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `APP_ID` VARCHAR(50) NOT NULL,
  `FIXTURE_ID` MEDIUMINT NOT NULL,
  `STATUS` VARCHAR(45) NULL,
  `CURRENT_STEP` SMALLINT NULL,
  `TEAM` VARCHAR(30) NOT NULL,
  `DATE_STARTED` DATE NULL,
  PRIMARY KEY (`ID`, `APP_ID`));


CREATE TABLE `step` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APP_ID` varchar(50) NOT NULL,
  `SEQUENCE_ID` varchar(50) NOT NULL,
  `FIXTURE_ID` mediumint(9) NOT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `NUMBER` smallint(6) DEFAULT NULL,
  `BET_ID` mediumint(9) DEFAULT NULL,
  PRIMARY KEY (`ID`, `APP_ID`, `SEQUENCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `sequence` (`ID`, `APP_ID`, `FIXTURE_ID`, `STATUS`, `CURRENT_STEP`, `TEAM`, `DATE_STARTED`) VALUES (<{ID: }>, <{FIXTURE_ID: }>, <{STATUS: }>, <{CURRENT_STEP: }>, <{TEAM: }>);


